apiVersion: v1
kind: PersistentVolumeClaim
namespace: default
metadata:
  name: pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M
